### ISSUE TITLE
请问下getUserOnlineState 这个对应方法在鸿蒙端是哪一个

### ISSUE THREAD

**Issue by zeroskylian** [wildfirechat/hm-chat#10]
在 wfc 中未发现对应方法，那么如何在鸿蒙段获取用户状态

**Comment by imndx** [comment]
已添加同名方法

**Comment by zeroskylian** [comment]
最新的有语法错误哦
![image](https://github.com/user-attachments/assets/57a47f28-9280-47c9-8533-a12cd6818afa)
