### ISSUE TITLE
getPCOnlineInfos 获取桌面端在线状态接口未实现

### ISSUE THREAD

**Issue by zeroskylian** [wildfirechat/hm-chat#12]

**Comment by zeroskylian** [comment]
![image](https://github.com/user-attachments/assets/d9c00ca8-6f4f-4a66-b0ee-604749707c16)

这个判断有点问题, 桌面端处于在线状态, 应该去掉双斜杠

**Comment by imndx** [comment]
好的，谢谢反馈
