### ISSUE TITLE
代码片段要优化下

### ISSUE THREAD

**Issue by Paul-IM-DEV** [wildfirechat/hm-chat#24]
[entry/src/main/ets/wfc/proto/proto.min.ets](https://github.com/wildfirechat/hm-chat/blob/8ecf77553a26bfe1e1cac82368300151895611f8/entry/src/main/ets/wfc/proto/proto.min.ets#L453)
```ts
    disconnect(disablePush = false, cleanSession = false) {
        self.userId = '';
        protoProxy.disconnect(disablePush, cleanSession);


        //sleep 1 second wait disconnect with im server
        let now = new Date();
        let exitTime = now.getTime() + 1000;
        while (true) {
            now = new Date();
            if (now.getTime() > exitTime) {
                return;
            }
        }
    }
```

AI 回复：
> 这段代码的目的是让程序在 1 秒钟后退出循环。虽然这段代码在逻辑上是正确的，但它有一些潜在的问题：
> 
> 1. 性能问题：这段代码会在循环中不断创建新的 Date 对象，这可能会导致性能问题，尤其是在高性能要求的应用中。
> 2. CPU 占用：这种忙等待（busy-waiting）方式会导致 CPU 占用率很高，因为它会不断地执行循环，直到条件满足。
> 为了避免这些问题，可以使用 setTimeout 或 setInterval 来实现延迟执行，而不是使用忙等待。

**Comment by imndx** [comment]
谢谢反馈，这段代码的本意就是卡住，等待彻底断开连接，才允许进行进一步操作。

由于这是一个非常低频的操作，应当没有太大的影响。
