### ISSUE TITLE
消息与通知设置开关还没支持

### ISSUE THREAD

**Issue by captain-miao** [wildfirechat/hm-chat#34]
消息与通知的开关，还没有。
主要是我调用里面的API，设置了也无效。

```
  ToggleItemView({
      title: '通知显示消息详情',
      isOn: !this.isHidden,
      showDivider: true,
      onChange: (isShow) => {
          wfc.setUserSetting(UserSettingScope.HiddenNotificationDetail, "", isShow ? "0" : "1", () => {
              this.isHidden = !isShow
          }, err => {
              this.isHidden = isShow
              showToast('设置失败 ' + err)
          })
      }
  })
```

**Comment by imndx** [comment]
`HiddenNotificationDetail`这个设置项是本地使用的，服务端不会做处理，你设置之后，只要下次获取这项`setting` 的值是正确的，那么就是设置成功的。

**Comment by imndx** [comment]
> > HiddenNotificationDetail
> 
> 不是，还是旧的值。
> 
> ```
> // 代码
> this.isHidden = wfc.getUserSetting(UserSettingScope.HiddenNotificationDetail, "0") === "1";
> ```

你可以，`userSetting`是`key-value`结构的，你设置的时候，`key`用的是`''`，而获取的时候，`key`使用的是`"0"`，故获取不到
