### ISSUE TITLE
七牛上传，还不支持七牛上传功能

### ISSUE THREAD

**Issue by captain-miao** [wildfirechat/hm-chat#41]
七牛上传，还不支持七牛上传功能

**Comment by imndx** [comment]
你好，请用最新代码确认一下，我们这边测试是支持的

**Comment by captain-miao** [comment]
> 你好，请用最新代码确认一下，我们这边测试是支持的

不是吧，七牛云的方式代码都注释了。

https://github.com/wildfirechat/hm-chat/blob/2495a6a0c685199b3ae9b070b00f82b1a23f83b3/client/src/main/ets/wfc/proto/proto.min.ets#L2312
