### ISSUE TITLE
请问如何自定义IM消息

### ISSUE THREAD

**Issue by zeroskylian** [wildfirechat/hm-chat#5]
这边调用
```
 registerMessageContent(name: string, flag: number, type: number) 
```
不好用

**Comment by zeroskylian** [comment]
![image](https://github.com/wildfirechat/hm-chat/assets/7043428/9466e093-e938-443c-bed2-af920891d088)
发现了这个方法，在这里面补充自定义消息生效了，但是在这里改了，注册方法就没啥用了吧

**Comment by imndx** [comment]
你好，建议参考[自定义消息](https://github.com/wildfirechat/hm-chat/blob/master/entry/src/main/ets/wfc_custom_message/README.md) 来实现

你上面的方案是可以实现，但不建议修改`wfc`目录下的内容，会导致后续合并代码会比较麻烦

**Comment by zeroskylian** [comment]
好的，我们这边同样建一个CustomMessageConfig 就可也了是吧？

![image](https://github.com/user-attachments/assets/7dcd359a-83f3-4b6d-90fe-269a87d092cb)

这个请勿修改的意思是？

**Comment by imndx** [comment]
> 好的，我们这边同样建一个CustomMessageConfig 就可也了是吧？
> 
> ![image](https://private-user-images.githubusercontent.com/7043428/348056078-7dcd359a-83f3-4b6d-90fe-269a87d092cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MzYwMTIsIm5iZiI6MTcyMDgzNTcxMiwicGF0aCI6Ii83MDQzNDI4LzM0ODA1NjA3OC03ZGNkMzU5YS04M2YzLTRiNmQtOTBmZS0yNjlhODdkMDkyY2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTNUMDE1NTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWM2YThkODc0NmIzMzJiZmM0YjJmN2VhOWYyMTg2ZDYwMjkyMmE4NzQyZDY5MjQzOTMwNmE5Nzg3YjdiZTI5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aSlupdZfqRcOfccwyuYaQm6xEzwLKFRwCb8FXsKoZXE)
> 
> 这个请勿修改的意思是？

就是别修改下面这个方法，在其上面有 *添加更多自定义消息* 的地方添加自定义消息

**Comment by zeroskylian** [comment]
![image](https://github.com/user-attachments/assets/d5183798-07aa-42d2-98db-4b3620786070)
如果这里不能改的话，哪里初始化 messagecontent 呢

**Comment by imndx** [comment]
> ![image](https://private-user-images.githubusercontent.com/7043428/348583011-d5183798-07aa-42d2-98db-4b3620786070.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMjg0MjMsIm5iZiI6MTcyMTAyODEyMywicGF0aCI6Ii83MDQzNDI4LzM0ODU4MzAxMS1kNTE4Mzc5OC0wN2FhLTQyZDItOThkYi00YjM2MjA3ODYwNzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTVUMDcyMjAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjNiNzk1OGU0MTQ5YmM5ODlmNjVlNWY2OGYxOTdjYjRiNWUxN2EzMmI5YzMxZTk3NmUxODkwZjU0YTQxYzI3MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZQAmgdbOZda6axIjU0LN93U5iGSyLEHst5pqyJRwUxk) 如果这里不能改的话，哪里初始化 messagecontent 呢

抱歉，注释写错了，请参考最新

**Comment by zeroskylian** [comment]
好的
