### ISSUE TITLE
文本消息的quoteInfo 不能正确发送

### ISSUE THREAD

**Issue by zeroskylian** [wildfirechat/hm-chat#7]
![image](https://github.com/user-attachments/assets/a0124f1d-9e20-4850-8688-47cb5c841a23)

```
let orgStr = JSON.stringify(obj); 
```
把内容转没了

**Comment by imndx** [comment]
请你对比下 demo，demo 上，应当是没问题


<img width="802" alt="image" src="https://github.com/user-attachments/assets/9e7793b9-c166-4b15-9787-45110e6a7180">

**Comment by zeroskylian** [comment]
解决了，我们这边的代码问题，不是最新的 sdk
