### ISSUE TITLE
getMentionedMessages 每次都会获取到已读的@提醒消息

### ISSUE THREAD

**Issue by zeroskylian** [wildfirechat/hm-chat#8]
getMentionedMessages 这个方法表现与 iOS 端不一致，每次都会获取到已读的@消息，iOS端只会获取到未读的提醒消息。请问是否是 bug

**Comment by heavyrain2012** [comment]
是问题，请等待我们修改

**Comment by heavyrain2012** [comment]
这个问题可能是对这个方法理解有误。getMentionedMessages方法的意思是获取@消息，包括已读和未读的@消息。如果想要获取到未读的@消息，需要用另外一个根据消息状态获取消息的方法来获取未读的@消息

**Comment by zeroskylian** [comment]
嗯，可能是我的理解有问题，在 iOS 端，有相应的方法拿未读的@消息
![image](https://github.com/user-attachments/assets/8baf8721-fe2a-4f03-b9fc-127da8f6a161)

但是在鸿蒙端，我没看到拿指定会话的@消息方法，我以为是一样的

**Comment by heavyrain2012** [comment]
鸿蒙端是 getMessagesByStatusV2

**Comment by zeroskylian** [comment]
请帮忙看下我这样调用是否正确，我使用getMessagesByStatusV2 拿不到数据，但是使用 getMentionedMessages可以
![image](https://github.com/user-attachments/assets/c64bc683-5fc7-4fe4-a178-fb41ccb703c2)

**Comment by zeroskylian** [comment]
可以，我的问题，我只前的代码是参考 demo 的，应该在获取后再标记
![image](https://github.com/user-attachments/assets/67deb4c6-ed31-4253-9a13-b4215d510fd2)
